### PR TITLE
license to AGPL

### PR DESCRIPTION
**Pull request by tesinormed**
requires the consent of **ALL** contributors
if you wish to use a different license, comment below.

### CODE REVIEW

**Comment by saksham4106** [comment]
smh

**Comment by tesinormed** [comment]
wat

**Comment by jojo2357** [comment]
I vote MIT because it has fewer requirements and hey, no patent use.

**Comment by tesinormed** [comment]
imagine patenting a discord bot 🤔

**Comment by jojo2357** [comment]
I find it silly to make people state all the changes they make especially on a bot it is really limiting especially since it isnt good out-of-the-box per se

**Comment by AG6Dev** [comment]
lmao

**Comment by tesinormed** [comment]
twat

**Comment by tesinormed** [comment]
arr bot

**Pull request closed without merging**
